// IMAGES: drop real photos from srivijayadurganursery.in into /public/img (WebP) using these names.
// Missing files gracefully fall back to a green gradient.
import map from './imgmap.js';
export const img = n => map[n] || `/img/${n}.webp`;
export const PHONE='+91 9160122226', MAIL='Svdn.plants@gmail.com';
export const STATS=[[75,'Years of Experience'],[1200000,'Saplings Every Year','12L+'],[45000,'Projects Completed'],[1700,'Farmers Collaborated']];
export const CATS=[['Fruit Plants','Mango, Guava, Citrus & more'],['Avenue Trees','Ideal for roadside & large-scale projects'],['Ornamental Plants','Exotic landscaping greens'],['Indoor Plants','Air-purifying & decorative plants'],['Bamboo & Grasses','Zen gardens & natural boundaries'],['Flowers','Vibrant flowers & greens'],['Palm Trees','Elegant and timeless landscape beauty'],['Shrubs','Beautiful greenery for gardens'],['Hangings','Hanging greens for creative spaces'],['Bonsai Plants','Peaceful and elegant miniature landscapes'],['Bougainvillea','Vibrant blooms that bring life and color']];
export const TEST=[["Rajesh K.", "Contractor", "We ordered 5,000 avenue trees for a highway project. SVDN handled the transport seamlessly to Maharashtra. Excellent plant health."], ["Surya Farms", "", "The best wholesale fruit plant suppliers in Andhra Pradesh. The mango and citrus saplings we received were robust and disease-free."], ["GreenScape Architects", "", "A trusted nursery near Rajahmundry. We rely on them for all our exotic ornamental requirements for luxury villa landscaping."]];
export const FAQ=[["Do you offer bulk plant delivery across India?", "Yes, we are premier wholesale plant suppliers in India. We cater to large-scale orders across all states using dedicated transport networks, ensuring plants arrive fresh."], ["Is there a minimum order quantity (MOQ)?", "Since we operate as a wholesale nursery, our minimum order quantities depend on plant sizes and loading constraints. Typically, we fulfill orders starting from half-truck loads. Contact us for specifics."], ["How do you ensure plant health during transit?", "Our saplings undergo root conditioning, are packed with moisture-retaining materials, and loaded carefully in well-ventilated transit vehicles to prevent shock or damage."], ["What varieties of fruit plants do you supply wholesale?", "We supply high-yield, verified grafts of Mango (Banganapalli, Alphonso, Totapuri), Guava (Taiwan Pink, Allahabad Safeda), Citrus, Sapota, Pomegranate, and Custard Apple tailored for commercial orchards."], ["Are Kadiyam nursery plants suitable for all Indian climates?", "Yes, the fertile soil and robust growing conditions in Kadiyapulanka create exceptionally hardy plants. However, our experts will recommend specific varieties based on your local microclimate zone."], ["Can you supply aged, large-girth avenue trees?", "Absolutely. We specialize in cultivating large-girth (3-inch to 10-inch trunk diameter) specimen avenue trees ready for immediate impact in landscaping and highway projects."]];
